---

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .

platforms:
  - name: tomcat
    groups:
      - tomcat
    image: idealista/jdk:8u222-stretch-openjdk-headless
    privileged: false
    command: '/lib/systemd/systemd'
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - '/run'
      - '/run/lock'
      - '/tmp'

provisioner:
  name: ansible
  inventory:
    group_vars:
      tomcat:
        tomcat_version: ${TOMCAT_VERSION}
verifier:
  name: ansible
  directory: ./tests
